'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import SpecialtiesSection from '@/components/SpecialtiesSection';
import MenuHighlightsSection from '@/components/MenuHighlightsSection';
import AboutSection from '@/components/AboutSection';
import GallerySection from '@/components/GallerySection';
import TestimonialsSection from '@/components/TestimonialsSection';
import BookingSection from '@/components/BookingSection';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <SpecialtiesSection />
        <MenuHighlightsSection />
        <AboutSection />
        <GallerySection />
        <TestimonialsSection />
        <BookingSection />
      </main>
    </>
  );
}